version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todos
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    image: todo-app:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db-data:
